import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:master_prompt/src/export/brief_pdf.dart';
import 'package:mp_core/mp_core.dart';

/// The fonts, read off disk rather than through an asset bundle, so this runs
/// as a plain test and the generated bytes are checkable on a Linux runner
/// instead of only by opening a file on a phone.
Future<ByteData> fromDisk(String key) async {
  final File f = File(
    '../packages/mp_design/${key.split('packages/mp_design/').last}',
  );
  return ByteData.view((await f.readAsBytes()).buffer);
}

const String body = '''
# Cocktail bar

A late-night bar interior, built to survive close inspection.

`task-id: bar` · 4+ review cycles

---

## 05 / RUBRIC

**SCORING** · Out of 100.

| # | Category | Weight |
|---|---|---:|
| 01 | Craft | 100 |

- One thing that must be true.

```
bar/
  DIRECTION.md
```
''';

void main() {
  late BriefFonts fonts;

  setUpAll(() async {
    fonts = await BriefFontLoader(fromDisk).fonts();
  });

  test('it produces a real PDF, not an empty one', () async {
    final Uint8List bytes = await BriefPdf(
      fonts: fonts,
    ).build(body: body, title: 'Cocktail bar', diff: BriefDiff.none);

    expect(
      String.fromCharCodes(bytes.take(5)),
      '%PDF-',
      reason: 'the header is the only cheap proof it is a PDF at all',
    );
    expect(
      String.fromCharCodes(bytes.skip(bytes.length - 6)).trim(),
      endsWith('%%EOF'),
      reason: 'a truncated PDF opens as a damaged file, not as nothing',
    );
  });

  test('the whole brief reaches the page, not just the first block', () async {
    final BriefPdf pdf = BriefPdf(fonts: fonts);
    final Uint8List small = await pdf.build(
      body: '# T\n\nOne line.',
      title: 'T',
      diff: BriefDiff.none,
    );
    final Uint8List full = await pdf.build(
      body: const PromptCompiler().compile(referenceSpecForPdf()).body,
      title: 'Skyline',
      diff: BriefDiff.none,
    );

    expect(
      full.length,
      greaterThan(small.length * 2),
      reason:
          'both embed the same fonts, so the difference between them is the '
          'brief — a full brief that weighed the same as one line would mean '
          'the pages were being dropped',
    );
  });

  test('the marked copy differs from the clean one', () async {
    final BriefDiff diff = BriefDiff.between(
      body.replaceAll('survive close inspection', 'look nice'),
      body,
    );
    expect(diff.isEmpty, isFalse);

    final BriefPdf pdf = BriefPdf(fonts: fonts);
    final Uint8List marked = await pdf.build(
      body: body,
      title: 'Cocktail bar',
      diff: diff,
    );
    final Uint8List clean = await pdf.build(
      body: body,
      title: 'Cocktail bar',
      diff: BriefDiff.none,
    );

    expect(
      marked.length,
      isNot(clean.length),
      reason:
          'the clean copy is the one to hand to someone who was not part of '
          'the review, so it has to actually be a different document rather '
          'than the same file with a different name',
    );
    expect(
      clean.length,
      lessThan(marked.length),
      reason: 'the marked one carries the revision note the clean one omits',
    );
  });

  test('every block kind lays out without throwing', () async {
    // If anything in the block set cannot be placed on a page, it fails here
    // rather than on a phone with the document half written.
    final BriefDocument d = BriefDocument.parse(body);
    expect(
      d.blocks.map((BriefBlock b) => b.kind).toSet(),
      containsAll(<BriefBlockKind>[
        BriefBlockKind.title,
        BriefBlockKind.section,
        BriefBlockKind.paragraph,
        BriefBlockKind.bullet,
        BriefBlockKind.table,
        BriefBlockKind.code,
        BriefBlockKind.rule,
      ]),
      reason: 'the fixture has to actually contain every shape it claims to',
    );

    await expectLater(
      BriefPdf(
        fonts: fonts,
      ).build(body: body, title: 'Cocktail bar', diff: BriefDiff.none),
      completes,
    );
  });
}

/// A spec broad enough to exercise every block kind, assembled from patch
/// lines the way a real one is.
MissionSpec referenceSpecForPdf() {
  final SpecPatchResult r = const SpecPatchParser().parse(
    '''
```mpspec
mission=A late-night cocktail bar interior, built to survive close inspection.
story=Arriving alone at midnight and deciding to stay.
scale=One room, 120 square metres, seating twenty.
audience=An interior architect who has built one.
tool=Blender 4.2
budget=100M tokens
coldstart=Open the file and render 01 at full resolution.
dir=cocktail_bar
total=100
exit=90
region+=Cocktail bar | Twenty seats with real service depth
relationship+=The bar and the room must share one sightline.
family+=Seating | stools and banquettes | min=30
avoid+=A hotel lobby with a counter in it.
palette+=Warm brass against deep green.
evidence+=1 | 01_arrival.png | Arrival | The first read of the room | hero
step+=1 | Shell | Build the room before anything in it.
rubric+=Craft | 100 | Holds up at 4K with no visible shortcuts.
critic+=Materials | Whether every surface reads as what it claims to be
failure+=A region built as a facade with no interior depth.
```
''',
    const MissionSpec(
      id: 'p',
      taskId: 'cocktail_bar',
      title: 'Cocktail bar',
      presetId: 'generic',
    ),
  );
  return r.spec.confirmProposals();
}
